### ISSUE TITLE
OS X installation documentation is out of date

### ISSUE THREAD

**Issue by bjoring** [melizalab/jill#18]
The jill prerequisites specify zmq22, but a more recent version is needed for installation (zmq @4.3.2_0 worked): `sudo port install scons boost libsamplerate libsndfile zmq22`

Also, it would be nice to add the information about the no-arf install like the info in the Debian section: `scons -Q --no-arf modules`

**Comment by dmeliza** [comment]
Fixed - this is in the wiki, so commit doesn't automatically close this issue.
